apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: quotes
  name: quotes
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/quotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotes
    spec:
      containers:
      - image: reisinge/quotes
        imagePullPolicy: Always
        name: quotes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
